-- Seed the initial set of chapters.

insert into public.chapters (
  name, city, state, zip_code, timezone, church,
  frat_night_day_of_week, frat_night_start_time, frat_night_end_time, frat_night_location
)
values
  ('St. Paul', 'Birmingham', 'AL', '35203', 'America/Chicago', 'St. Paul Catholic Church', 'tuesday', '18:30', '20:30', 'St. Paul Catholic Church'),
  ('Holy Spirit', 'Huntsville', 'AL', '35802', 'America/Chicago', 'Holy Spirit Catholic Church', 'tuesday', '18:30', '20:30', 'Holy Spirit Catholic Church'),
  ('St. Isidore', 'Yuba City', 'CA', '95991', 'America/Los_Angeles', 'St. Isidore Catholic Church', 'tuesday', '18:30', '20:30', 'St. Isidore Catholic Church'),
  ('St. Patrick', 'Jacksonville', 'FL', '32218', 'America/New_York', 'St. Patrick Catholic Church', 'tuesday', '18:30', '20:30', 'St. Patrick Catholic Church'),
  ('Christ the King', 'Tampa', 'FL', '33609', 'America/New_York', 'Christ the King Catholic Church', 'tuesday', '18:30', '20:30', 'Christ the King Catholic Church'),
  ('Mary Our Queen', 'Peachtree Corners', 'GA', '30092', 'America/New_York', 'Mary Our Queen Catholic Church', 'tuesday', '18:30', '20:30', 'Mary Our Queen Catholic Church'),
  ('St. Louis de Montfort', 'Fishers', 'IN', '46038', 'America/Indiana/Indianapolis', 'St. Louis de Montfort Catholic Church', 'tuesday', '18:30', '20:30', 'St. Louis de Montfort Catholic Church'),
  ('St. Elizabeth Ann Seton', 'Fort Wayne', 'IN', '46804', 'America/Indiana/Indianapolis', 'St. Elizabeth Ann Seton Catholic Church', 'tuesday', '18:30', '20:30', 'St. Elizabeth Ann Seton Catholic Church'),
  ('St. James', 'Elizabethtown', 'KY', '42701', 'America/Chicago', 'St. James Catholic Church', 'tuesday', '18:30', '20:30', 'St. James Catholic Church'),
  ('Sacred Heart of Jesus', 'Baton Rouge', 'LA', '70802', 'America/Chicago', 'Sacred Heart of Jesus Catholic Church', 'tuesday', '18:30', '20:30', 'Sacred Heart of Jesus Catholic Church'),
  ('St. Margaret of Scotland', 'Lake Charles', 'LA', '70601', 'America/Chicago', 'St. Margaret of Scotland Catholic Church', 'tuesday', '18:30', '20:30', 'St. Margaret of Scotland Catholic Church'),
  ('St. Bridget', 'Schriever', 'LA', '70395', 'America/Chicago', 'St. Bridget Catholic Church', 'tuesday', '18:30', '20:30', 'St. Bridget Catholic Church'),
  ('Corpus Christi', 'E. Sandwich', 'MA', '02537', 'America/New_York', 'Corpus Christi Catholic Church', 'tuesday', '18:30', '20:30', 'Corpus Christi Catholic Church'),
  ('St. Ann''s', 'Charlotte', 'NC', '28209', 'America/New_York', 'St. Ann''s Catholic Church', 'tuesday', '18:30', '20:30', 'St. Ann''s Catholic Church'),
  ('St. Aloysius', 'Hickory', 'NC', '28601', 'America/New_York', 'St. Aloysius Catholic Church', 'tuesday', '18:30', '20:30', 'St. Aloysius Catholic Church'),
  ('St. Mark', 'Huntersville', 'NC', '28078', 'America/New_York', 'St. Mark Catholic Church', 'tuesday', '18:30', '20:30', 'St. Mark Catholic Church'),
  ('St. John the Baptist', 'Tryon', 'NC', '28782', 'America/New_York', 'St. John the Baptist Catholic Church', 'tuesday', '18:30', '20:30', 'St. John the Baptist Catholic Church'),
  ('St. Catherine of Siena', 'Wake Forest', 'NC', '27587', 'America/New_York', 'St. Catherine of Siena Catholic Church', 'tuesday', '18:30', '20:30', 'St. Catherine of Siena Catholic Church'),
  ('Our Lady of Pompeii', 'Lancaster', 'NY', '14086', 'America/New_York', 'Our Lady of Pompeii Catholic Church', 'tuesday', '18:30', '20:30', 'Our Lady of Pompeii Catholic Church'),
  ('St. Mary Help of Christians', 'Aiken', 'SC', '29801', 'America/New_York', 'St. Mary Help of Christians Catholic Church', 'tuesday', '18:30', '20:30', 'St. Mary Help of Christians Catholic Church'),
  ('Saint Mary''s', 'Greenville', 'SC', '29601', 'America/New_York', 'Saint Mary''s Catholic Church', 'tuesday', '18:30', '20:30', 'Saint Mary''s Catholic Church'),
  ('St. Andrew', 'Myrtle Beach', 'SC', '29577', 'America/New_York', 'St. Andrew Catholic Church', 'tuesday', '18:30', '20:30', 'St. Andrew Catholic Church'),
  ('Prince of Peace', 'Taylors', 'SC', '29687', 'America/New_York', 'Prince of Peace Catholic Church', 'tuesday', '18:30', '20:30', 'Prince of Peace Catholic Church'),
  ('St. Philip', 'Franklin', 'TN', '37064', 'America/Chicago', 'St. Philip Catholic Church', 'tuesday', '18:30', '20:30', 'St. Philip Catholic Church'),
  ('Holy Ghost', 'Knoxville', 'TN', '37917', 'America/New_York', 'Holy Ghost Catholic Church', 'tuesday', '18:30', '20:30', 'Holy Ghost Catholic Church'),
  ('Sacred Heart', 'Lawrenceburg', 'TN', '38464', 'America/Chicago', 'Sacred Heart Catholic Church', 'tuesday', '18:30', '20:30', 'Sacred Heart Catholic Church'),
  ('St. Rose of Lima', 'Murfreesboro', 'TN', '37130', 'America/Chicago', 'St. Rose of Lima Catholic Church', 'tuesday', '18:30', '20:30', 'St. Rose of Lima Catholic Church'),
  ('Overbrook Catholic School', 'Nashville', 'TN', '37205', 'America/Chicago', 'Overbrook Catholic School Catholic Church', 'tuesday', '18:30', '20:30', 'Overbrook Catholic School Catholic Church'),
  ('St. Edward''s', 'Nashville', 'TN', '37211', 'America/Chicago', 'St. Edward''s Catholic Church', 'tuesday', '18:30', '20:30', 'St. Edward''s Catholic Church'),
  ('Nativity', 'Thompsons Station', 'TN', '37179', 'America/Chicago', 'Nativity Catholic Church', 'tuesday', '18:30', '20:30', 'Nativity Catholic Church'),
  ('Our Lady of the Lake', 'Hendersonville', 'TN', '37075', 'America/Chicago', 'Our Lady of the Lake Catholic Church', 'tuesday', '18:30', '20:30', 'Our Lady of the Lake Catholic Church'),
  ('Our Lady Star of the Sea', 'Bremerton', 'WA', '98337', 'America/Los_Angeles', 'Our Lady Star of the Sea Catholic Church', 'tuesday', '18:30', '20:30', 'Our Lady Star of the Sea Catholic Church'),
  ('Holy Redeemer', 'Vancouver', 'WA', '98684', 'America/Los_Angeles', 'Holy Redeemer Catholic Church', 'tuesday', '18:30', '20:30', 'Holy Redeemer Catholic Church');
