-- Seed the Year 1 Field Guide weekly content (weeks, quotes, and daily
-- devotionals), authored in
-- fraternus_mobile_app/data/field_guide/field_guide_daily_devotional_content.yaml.
-- Correlates the weeks insert to the quotes/devotionals inserts by
-- week_number (unique per field_guide_weeks) rather than relying on
-- multi-row INSERT...RETURNING ordering, same pattern as
-- 20260820001000_seed_events_frat_nights.sql.

with inserted_weeks as (
  insert into public.field_guide_weeks (
    year_number, week_number, virtue, vice, extreme, reflection, choleric_application, choleric_vices, sanguine_application, sanguine_vices, melancholic_application, melancholic_vices, phlegmatic_application, phlegmatic_vices
  )
  values
    (1, 1, 'Humility', 'Pride', 'Self-Loathing', 'Pride has a deep root. Every vice grows from it. This week, through humility you will take note of how often you want to be right, to be seen, to be above others. Pride was the first sin of man, and we fight it until our last breath, learning to trust God. Humility is not weakness. It is the quiet strength of a man who knows his place before God and does not need applause, recognition, or control, because he lives in the truth.', 'Struggles most with humility. Their natural drive to lead and dominate makes submission feel like defeat.', 'Arrogance, contempt for weakness, need to be right.', 'Craves attention and approval, making hidden service deeply uncomfortable.', 'Vanity, name-dropping, exaggerating accomplishments', 'Can mistake self-criticism for humility. True humility requires accepting imperfection without despair.', 'Intellectual pride, perfectionism disguised as high standards', 'Appears humble but may simply be avoiding conflict. Genuine humility requires active surrender, not passive withdrawal.', 'False modesty, using humility as an excuse for inaction'),
    (1, 2, 'Generosity', 'Greed', 'Wastefulness', 'Generosity fights greed by holding loosely onto material goods instead of gripping them. Being generous extends to our time, attention, comfort — anything you clutch too tightly or desire too fiercely. A generous man holds nothing too tightly and is like God in being ready to give himself and his goods away. Being able to give something away is proof that you are not ruled by it but are truly free.', 'Might give strategically but struggles to give without controlling how the gift is used.', 'Transactional giving, using generosity as leverage.', 'Generous in the moment but inconsistent — easily distracted from sustained giving.', 'Impulsive spending, promising more than they deliver.', 'Fears scarcity deeply, making generosity feel risky and draining.', 'Hoarding resources ''just in case,'' withholding emotionally.', 'Will give when asked but might be taken advantage of or fail to recognize where he ought to give.', 'Stinginess with effort, giving the minimum to avoid tension.'),
    (1, 3, 'Chastity', 'Lust', 'Prudishness', 'Chastity frees us from the vice of lust, which is selfish impurity, the habit of using people and things selfishly and for pleasure alone. The chaste man is not only free from many vices, but he has greater purity of intention and consistency in love. Because he flees temptations to lust, when the time comes, he is free to love fully. This virtue requires daily vigilance.', 'Strong-willed enough to set boundaries but tempted to use intensity as justification for indulgence.', 'Rationalizing excess, dominating relationships, objectifying through conquest.', 'Drawn to pleasure and novelty — chastity demands discipline the sanguine finds exhausting.', 'Flirtation, lack of boundaries, dangerous screen habits.', 'Idealizes purity but can spiral into scrupulosity when they fail — grace is essential.', 'Fantasy and escapism, obsessive guilt, emotional dependency.', 'May avoid temptation through passivity rather than virtue — true chastity is an active choice.', 'Passive consumption, avoiding accountability, drifting into habitual sin.'),
    (1, 4, 'Patience', 'Anger', 'Indifference', 'Patience undoes the vice of wrath, which is disordered anger. The patient man is not easily provoked, is not given to outbursts or wrath, and deals calmly with life''s difficulties. He is not indifferent to difficulties but responds with order. He is especially careful with his reactions and is not surprised by his own defects or those of others. Patience is not weakness, but a form of enduring strength.', 'Patience is the choleric''s greatest battle — they want results now and view waiting as weakness.', 'Explosive anger, impatience with incompetence, bulldozing people.', 'Patient in social settings but deeply impatient with tedious or unglamorous tasks.', 'Restlessness, abandoning projects midway, emotional volatility.', 'Patient with ideas but impatient with people who do not meet their standards.', 'Resentment, cold anger, passive-aggressive withdrawal.', 'Naturally patient but may confuse patience with avoidance — true patience endures difficulty but does not ignore it.', 'Stubbornness disguised as patience, procrastination, conflict avoidance.'),
    (1, 5, 'Temperance', 'Gluttony', 'Deficiency', 'Temperance frees us from the vice of gluttony, which is overindulgence in food or drink. Temperance makes sure that legitimate needs and appetites always act as servants instead of tyrants. Temperance is not deprivation; it includes freedom from the tyranny of more, which includes excess desires for knowledge, honor, and comfort.', 'Driven to excess in work and ambition — temperance means choosing rest and limits.', 'Workaholism, excessive intensity, burnout cycles.', 'Loves pleasure in all forms — temperance is the hardest discipline for the sanguine to sustain.', 'Overindulgence, inability to say no, living for the next thrill.', 'Tends toward excess in thought and emotion — temperance means moderation of the inner life too.', 'Overthinking, emotional indulgence, excessive self-analysis.', 'Tempted by comfort and ease — temperance asks for deliberate discomfort resistance.', 'Laziness with food and rest, choosing the path of least resistance.'),
    (1, 6, 'Kindness', 'Envy', 'Timidity', 'Kindness frees us from the sin of envy, which is when the goods of others causes our sadness. Envy whispers that another man''s success diminishes yours. Envy causes us to compare ourselves with others, desire what they have, and be blind to our own blessings. Kindness is the antidote (timidity), but a genuine orientation toward the good of others. A kind man is free, because he is not competing.', 'Finds kindness inefficient — has a hard time caring how others feel.', 'Harshness, bluntness that wounds, dismissing others'' feelings.', 'Naturally warm but kindness must go deeper than charm — it must cost something.', 'Superficial friendliness, avoiding hard conversations, fickle loyalty.', 'Might be kind to a select few but may hold grudges and withhold it from those who disappoint them.', 'Judgmental spirit, withholding warmth as punishment, envy of others'' ease.', 'Gentle by nature but true kindness requires initiative — reaching out, not just avoiding harm or conflict.', 'Easy-going but might lack the effort it takes to correct and give in kindness.'),
    (1, 7, 'Diligence', 'Sloth', 'Workaholism', 'Diligence frees us from the vice of sloth, which is a deceptive snare. It does not always look like lying on a couch. It comes also in busyness, distraction, and it even causes us to be sad about things we know are good, like the spiritual life. Sloth is about avoiding our dignity and calling as sons of God. Diligence is not workaholism; it is the disciplined habit of doing what matters and having zeal for what God wants.', 'Naturally diligent but risks workaholism — true diligence is ordered, not obsessive.', 'Overwork, neglecting relationships for results, perfectionism.', 'Starts strong but fades fast — diligence means finishing what enthusiasm began.', 'Procrastination, half-finished projects, easily bored by routine.', 'Diligent in what interests them but paralyzed by tasks that feel meaningless.', 'Analysis paralysis, perfectionism that prevents completion, avoidance of mundane duties.', 'Struggles most with diligence — the effort to begin is the highest hurdle.', 'Laziness, procrastination, doing the bare minimum.')
  returning id, week_number
)
insert into public.field_guide_week_quotes (field_guide_week_id, quote, author)
select w.id, q.quote, q.author
from inserted_weeks w
join (
  values
    (1, 'It is the humble man whom God protects and liberates; it is the humble whom He loves and consoles. To the humble He turns and upon them bestows great grace, that after their humiliation He may raise them up to glory.', 'Thomas à Kempis'),
    (1, 'Many people try to escape temptations, only to fall more deeply. We cannot conquer simply by fleeing, but by patience and true humility, we become stronger than all our enemies.', 'Thomas à Kempis'),
    (2, 'The love of Jesus is noble and generous; it spurs us on to do great things and excites us to desire always that which is most perfect.', 'Thomas à Kempis'),
    (2, 'But grace is bountiful and openhearted, avoids selfishness, is contented with little, and judges it a more blessed thing to give rather than to receive.', 'Thomas à Kempis'),
    (3, 'No chastity is secure if You do not guard it.', 'Thomas à Kempis'),
    (3, 'Love is circumspect, humble, and upright. It is neither soft nor light, nor intent upon vain things. It is sober and chaste, firm and quiet, guarded in all the senses.', 'Thomas à Kempis'),
    (4, 'Dispose thyself to patience rather than consolation, and to bear the Cross rather than to rejoice.', 'Thomas à Kempis'),
    (4, 'Turn thine eyes back upon thyself, and see thou judge not the doings of others.', 'Thomas à Kempis'),
    (5, 'It is then by resisting our passions that we are to find true peace of heart, and not by being slaves to them.', 'Thomas à Kempis'),
    (5, 'It is a sign of great purity and interior confidence to refuse comfort from any created thing.', 'Thomas à Kempis'),
    (6, 'Be humble and peaceable, and Jesus will be with thee.', 'Thomas à Kempis'),
    (6, 'To have no opinion of ourselves, and to think always well and commendably of others, is great wisdom and high perfection.', 'Thomas à Kempis'),
    (7, 'Be watchful and diligent in God''s service and often think of why you left the world and came here. Was it not that you might live for God and become a spiritual man?', 'Thomas à Kempis'),
    (7, 'Without care and diligence, you will never acquire virtue.', 'Thomas à Kempis')
) as q(week_number, quote, author)
on q.week_number = w.week_number;

insert into public.field_guide_daily_devotionals (
  field_guide_week_id, day_number, identity_reading, wisdom_quote, wisdom_author, sword_option_1, sword_option_2, spade_prompt, closing_prayer, closing_prayer_author
)
select w.id, d.day_number, d.identity_reading, d.wisdom_quote, d.wisdom_author, d.sword_option_1, d.sword_option_2, d.spade_prompt, d.closing_prayer, d.closing_prayer_author
from public.field_guide_weeks w
join (
  values
    (1, 1, 'By God''s grace, I am a man who is humble, avoiding both pride and self loathing.', 'He who knows himself well, is mean in his own eyes, and is not delighted with being praised by men.', 'Thomas à Kempis', 'The pull toward control, self-reliance, or proving myself; I will let God lead instead.', 'The pull toward comfort, approval, or staying invisible; I will serve without recognition instead.', 'Where did I notice pride or humility at work in me today?', 'God, always the same, let me know myself, let me know You. Let me know You, O Lord, who know me; let me know You, as I am known. Amen.', 'St. Augustine'),
    (1, 2, 'By God''s grace, I am a man who is humble, avoiding both pride and self loathing.', 'We are all frail: but see thou think no one more frail than myself.', 'Thomas à Kempis', 'The temptation to manage everything myself; I will trust God and act with humility instead.', 'The temptation to avoid sacrifice or difficulty; I will choose courage and duty instead.', 'Where did I notice pride or humility at work in me today?', 'God, always the same, let me know myself, let me know You. Let me know You, O Lord, who know me; let me know You, as I am known. Amen.', 'St. Augustine'),
    (1, 3, 'By God''s grace, I am a man who is humble, avoiding both pride and self loathing.', 'The more humble a man is in himself, and more subject to God, the more wise will he be in all things, and the more at peace.', 'Thomas à Kempis', 'The desire to succeed, impress, or stay in control; I will live as a son instead.', 'The desire to remain comfortable, unnoticed, or affirmed; I will step forward in service instead.', 'Where did I notice pride or humility at work in me today?', 'God, always the same, let me know myself, let me know You. Let me know You, O Lord, who know me; let me know You, as I am known. Amen.', 'St. Augustine'),
    (1, 4, 'By God''s grace, I am a man who is humble, avoiding both pride and self loathing.', 'We have reason, therefore, to humble ourselves and never to think much of ourselves since we are so frail and inconstant.', 'Thomas à Kempis', 'The urge to rely on my own strength; I will depend on grace instead.', 'The urge to coast, delay or stay passive; I will embrace discipline instead.', 'Where did I notice pride or humility at work in me today?', 'God, always the same, let me know myself, let me know You. Let me know You, O Lord, who know me; let me know You, as I am known. Amen.', 'St. Augustine'),
    (1, 5, 'By God''s grace, I am a man who is humble, avoiding both pride and self loathing.', 'Thou has not anything in which thou canst glory, but many things for which thou oughtst to humble thyself, for thou art much weaker than thou art able to comprehend.', 'Thomas à Kempis', 'The pull toward pride, pressure, or perfectionism; I will receive today with humility instead.', 'The pull toward ease, distraction, or pleasing others; I will choose to please God and not man or self.', 'Where did I notice pride or humility at work in me today?', 'God, always the same, let me know myself, let me know You. Let me know You, O Lord, who know me; let me know You, as I am known. Amen.', 'St. Augustine'),
    (1, 6, 'By God''s grace, I am a man who is humble, avoiding both pride and self loathing.', 'Therefore thou must not ascribe anything of good to thyself, nor attribute virtue to any man, but give all to God, without whom man is nothing.', 'Thomas à Kempis', 'The temptation to control outcomes or prove my strength; I will give credit to God for the work He does in me.', 'The temptation to hide, withdraw, or avoid discomfort; I will love through sacrifice instead.', 'Where did I notice pride or humility at work in me today?', 'God, always the same, let me know myself, let me know You. Let me know You, O Lord, who know me; let me know You, as I am known. Amen.', 'St. Augustine'),
    (1, 7, 'By God''s grace, I am a man who is humble, avoiding both pride and self loathing.', 'The saints that are highest in the sight of God are the least in their own eyes; and the more glorious they are the more humble they are in themselves.', 'Thomas à Kempis', 'The battle against pride and self-reliance; I will acknowledge how much I need others.', 'The battle against comfort and passivity; I will answer the call to serve instead.', 'Where did I notice pride or humility at work in me today?', 'God, always the same, let me know myself, let me know You. Let me know You, O Lord, who know me; let me know You, as I am known. Amen.', 'St. Augustine'),
    (2, 1, 'By God''s grace, I am a man who is generous, avoiding both greed and wastefulness.', 'He is truly great, who is great in charity.', 'Thomas à Kempis', 'The pull toward hoarding, control, or withholding; I will give freely instead.', 'The pull toward impulsiveness, stinginess, or passivity; I will give consistently instead.', 'Where did I notice greed or generosity at work in me today?', 'Take, Lord, and receive all my liberty, my memory, my understanding, and my entire will... Give me only your love and your grace, that is enough for me.', 'St. Ignatius of Loyola'),
    (2, 2, 'By God''s grace, I am a man who is generous, avoiding both greed and wastefulness.', 'Without charity the outward work profiteth nothing: but whatever is done out of charity, be it ever so little and contemptible, all becomes fruitful.', 'Thomas à Kempis', 'The temptation to protect what is mine too tightly; I will acknowledge it all belongs to God.', 'The temptation to avoid inconvenience or effort; I will give with readiness instead.', 'Where did I notice greed or generosity at work in me today?', 'Take, Lord, and receive all my liberty, my memory, my understanding, and my entire will... Give me only your love and your grace, that is enough for me.', 'St. Ignatius of Loyola'),
    (2, 3, 'By God''s grace, I am a man who is generous, avoiding both greed and wastefulness.', 'He that has true and perfect charity, seeks himself in no one thing, but desires only the glory of God, in all things.', 'Thomas à Kempis', 'The desire to keep control, conserve strength, or stay guarded; I will offer myself generously instead.', 'The desire to spend carelessly, drift, or hold back when needed; I will give with purpose instead.', 'Where did I notice greed or generosity at work in me today?', 'Take, Lord, and receive all my liberty, my memory, my understanding, and my entire will... Give me only your love and your grace, that is enough for me.', 'St. Ignatius of Loyola'),
    (2, 4, 'By God''s grace, I am a man who is generous, avoiding both greed and wastefulness.', 'Endeavor, My son, rather to do the will of another than thine own.', 'Thomas à Kempis', 'The urge to measure, calculate, or withhold from others; I will give without counting the cost instead.', 'The urge to delay, avoid, or neglect opportunities to serve; I will respond promptly instead.', 'Where did I notice greed or generosity at work in me today?', 'Take, Lord, and receive all my liberty, my memory, my understanding, and my entire will... Give me only your love and your grace, that is enough for me.', 'St. Ignatius of Loyola'),
    (2, 5, 'By God''s grace, I am a man who is generous, avoiding both greed and wastefulness.', 'If you have wealth, do not glory in it, nor in friends because they are powerful, but in God Who gives all things and Who desires above all to give Himself.', 'Thomas à Kempis', 'The pull toward self-protection, scarcity, or mistrust; I will give knowing that God provides abundantly.', 'The pull toward comfort, distraction, or inconsistency; I will give faithfully instead.', 'Where did I notice greed or generosity at work in me today?', 'Take, Lord, and receive all my liberty, my memory, my understanding, and my entire will... Give me only your love and your grace, that is enough for me.', 'St. Ignatius of Loyola'),
    (2, 6, 'By God''s grace, I am a man who is generous, avoiding both greed and wastefulness.', 'No one, however, is more wealthy than such a man; no one is more powerful, no one is freer than he who knows how to leave all things and think of himself as the least of all.', 'Thomas à Kempis', 'The temptation to cling to time, possessions, or prestige; I will pour myself out for others instead.', 'The temptation to act only when convenient or emotionally moved; I will give myself to someone that won''t recognize it.', 'Where did I notice greed or generosity at work in me today?', 'Take, Lord, and receive all my liberty, my memory, my understanding, and my entire will... Give me only your love and your grace, that is enough for me.', 'St. Ignatius of Loyola'),
    (2, 7, 'By God''s grace, I am a man who is generous, avoiding both greed and wastefulness.', 'Nature has regard for temporal wealth and rejoices in earthly gains. It is sad over a loss and irritated by a slight, injurious word. But grace looks to eternal things and does not cling to those which are temporal.', 'Thomas à Kempis', 'The battle against withholding and self-protection; I will open my heart and treasure to someone I don''t think "deserves it."', 'The battle giving things away to be like or to keep peace; I will ask God where I am being called to be generous.', 'Where did I notice greed or generosity at work in me today?', 'Take, Lord, and receive all my liberty, my memory, my understanding, and my entire will... Give me only your love and your grace, that is enough for me.', 'St. Ignatius of Loyola'),
    (3, 1, 'By God''s grace, I am a man who is chaste, avoiding being both lustful and puritanical.', 'With two wings a man is lifted up above earthly things: that is, with simplicity and purity.', 'Thomas à Kempis', 'The pull toward rationalization, fantasy, or conquest; I will guard my heart instead.', 'The pull toward overindulgence, careless pleasures, or indiscipline; I will choose discipline instead.', 'Where did I notice lust or chastity at work in me today?', 'Grant us purity of heart and strength of purpose, so that no selfish passion may hinder us from knowing your will, no weakness from doing it.', 'St. Augustine'),
    (3, 2, 'By God''s grace, I am a man who is chaste, avoiding being both lustful and puritanical.', 'Simplicity aims at God, purity takes hold of Him and tastes Him.', 'Thomas à Kempis', 'The temptation to indulge secret desires or justify impurity; I will acknowledge the truth of my weakness.', 'The temptation to chase comfort, stimulation, or escape; I will find a specific way to deny my flesh.', 'Where did I notice lust or chastity at work in me today?', 'Grant us purity of heart and strength of purpose, so that no selfish passion may hinder us from knowing your will, no weakness from doing it.', 'St. Augustine'),
    (3, 3, 'By God''s grace, I am a man who is chaste, avoiding being both lustful and puritanical.', 'If thou wert good and pure within, then wouldst thou discern all things without impediment and understand them rightly.', 'Thomas à Kempis', 'The desire to possess, control, or feed the imagination wrongly; I will honor others with reverence instead.', 'The desire to drift into dangerous distraction or excess; I will be careful to avoid idleness.', 'Where did I notice lust or chastity at work in me today?', 'Grant us purity of heart and strength of purpose, so that no selfish passion may hinder us from knowing your will, no weakness from doing it.', 'St. Augustine'),
    (3, 4, 'By God''s grace, I am a man who is chaste, avoiding being both lustful and puritanical.', 'Nothing so defiles and entangles the heart of man as impure love to created things.', 'Thomas à Kempis', 'The urge to entertain temptation or test my limits; I will flee the occasions of sin instead.', 'The urge to seek immediate pleasure or avoid restraint; I will embrace discipline with freedom instead.', 'Where did I notice lust or chastity at work in me today?', 'Grant us purity of heart and strength of purpose, so that no selfish passion may hinder us from knowing your will, no weakness from doing it.', 'St. Augustine'),
    (3, 5, 'By God''s grace, I am a man who is chaste, avoiding being both lustful and puritanical.', 'A pure conscience affords a great confidence in God.', 'Thomas à Kempis', 'The pull toward pride, secrecy, or misuse of desire; I will walk in integrity instead.', 'The pull toward indulgence, laziness, or sensual excess; I will train my appetites instead.', 'Where did I notice lust or chastity at work in me today?', 'Grant us purity of heart and strength of purpose, so that no selfish passion may hinder us from knowing your will, no weakness from doing it.', 'St. Augustine'),
    (3, 6, 'By God''s grace, I am a man who is chaste, avoiding being both lustful and puritanical.', 'The greatest obstacle, indeed, the only obstacle, is that we are not free from passions and lusts that we do not try to follow the perfect way of the saints. Thus when we encounter some slight difficulty, we are too easily dejected and turn to human consolations.', 'Thomas à Kempis', 'The temptation to objectify, fantasize, or seek selfish gratification; I will choose sacrificial love instead.', 'The temptation to numb myself with comfort or entertainment; I will remain vigilant instead.', 'Where did I notice lust or chastity at work in me today?', 'Grant us purity of heart and strength of purpose, so that no selfish passion may hinder us from knowing your will, no weakness from doing it.', 'St. Augustine'),
    (3, 7, 'By God''s grace, I am a man who is chaste, avoiding being both lustful and puritanical.', 'It is vanity to follow the lusts of the body and to desire things for which severe punishment later must come.', 'Thomas à Kempis', 'The battle against the pride that forgets weakness; I will recognize my need for accountability.', 'The battle against indulgence and lack of discipline; I will live with purity and strength instead.', 'Where did I notice lust or chastity at work in me today?', 'Grant us purity of heart and strength of purpose, so that no selfish passion may hinder us from knowing your will, no weakness from doing it.', 'St. Augustine'),
    (4, 1, 'By God''s grace, I am a man who is patient, avoiding both anger and indifference.', 'He does well who regards rather the common good than his own will.', 'Thomas à Kempis', 'The pull toward disappointment in others or forcing outcomes; I will trust God''s timing instead.', 'The pull toward restlessness, avoidance, or complaint; I will endure with joy instead.', 'Where did I notice anger or patience at work in me today?', 'O my God, give me a true faith, a firm hope, and a perfect charity; grant that I may always do Your holy will, and follow You with steadfast love.', 'St. Alphonsus Liguori'),
    (4, 2, 'By God''s grace, I am a man who is patient, avoiding both anger and indifference.', 'Endeavor to be patient in supporting the defects and infirmities of others, of what kind soever; because thou also hast many things which others must bear withal.', 'Thomas à Kempis', 'The temptation to control situations or react harshly; I will respond calmly instead.', 'The temptation to give up, withdraw, or complain; I will persevere faithfully instead.', 'Where did I notice anger or patience at work in me today?', 'O my God, give me a true faith, a firm hope, and a perfect charity; grant that I may always do Your holy will, and follow You with steadfast love.', 'St. Alphonsus Liguori'),
    (4, 3, 'By God''s grace, I am a man who is patient, avoiding both anger and indifference.', 'If thou canst not make thyself such a one as thou wouldst, how canst thou expect to have another according to thy liking?', 'Thomas à Kempis', 'The desire to demand results, recognition, or immediate change; I will wait with reasonable patience instead.', 'The desire to escape discomfort, delay responsibility, or lose heart; I will remain steadfast instead.', 'Where did I notice anger or patience at work in me today?', 'O my God, give me a true faith, a firm hope, and a perfect charity; grant that I may always do Your holy will, and follow You with steadfast love.', 'St. Alphonsus Liguori'),
    (4, 4, 'By God''s grace, I am a man who is patient, avoiding both anger and indifference.', 'We are willing that others should be bound up by laws, and we are unwilling ourselves to be restrained by any means.', 'Thomas à Kempis', 'The urge to correct, pressure, or overpower others; I will bear with others in charity instead.', 'The urge to avoid difficulty or seek constant ease; I will embrace endurance instead.', 'Where did I notice anger or patience at work in me today?', 'O my God, give me a true faith, a firm hope, and a perfect charity; grant that I may always do Your holy will, and follow You with steadfast love.', 'St. Alphonsus Liguori'),
    (4, 5, 'By God''s grace, I am a man who is patient, avoiding both anger and indifference.', 'He who knows how to suffer will enjoy much peace.', 'Thomas à Kempis', 'The pull toward frustration, impatience, or bitterness; I will receive interruptions peacefully instead.', 'The pull toward distraction, discouragement, or grumbling; I will carry today''s burden gladly instead.', 'Where did I notice anger or patience at work in me today?', 'O my God, give me a true faith, a firm hope, and a perfect charity; grant that I may always do Your holy will, and follow You with steadfast love.', 'St. Alphonsus Liguori'),
    (4, 6, 'By God''s grace, I am a man who is patient, avoiding both anger and indifference.', 'A patient man hath a great and wholesome purgatory, who, receiving injuries, is more concerned at the person''s sin than his own wrong.', 'Thomas à Kempis', 'The temptation to take matters into my own hands; I will surrender the outcome to God and others instead.', 'The temptation to become passive or unreliable; I will continue faithfully instead.', 'Where did I notice anger or patience at work in me today?', 'O my God, give me a true faith, a firm hope, and a perfect charity; grant that I may always do Your holy will, and follow You with steadfast love.', 'St. Alphonsus Liguori'),
    (4, 7, 'By God''s grace, I am a man who is patient, avoiding both anger and indifference.', 'If thou wilt be borne with, bear also with another.', 'Thomas à Kempis', 'The battle against anger and the need to control; I will rest in God''s providence instead.', 'The battle against willful distraction and restless avoidance; I will focus on my commitments and responsibility.', 'Where did I notice anger or patience at work in me today?', 'O my God, give me a true faith, a firm hope, and a perfect charity; grant that I may always do Your holy will, and follow You with steadfast love.', 'St. Alphonsus Liguori'),
    (5, 1, 'By God''s grace, I am a man who is temperate, avoiding both gluttony and deficiency.', 'Bridle gluttony, and thou shalt the easier restrain all carnal inclinations.', 'Thomas à Kempis', 'The pull toward excess, intensity, or overthinking; I will embrace ordered limits instead.', 'The pull toward indulgence, comfort, or the path of ease; I will choose moderation instead.', 'Where did I notice excess or temperance at work in me today?', 'Take, Lord, and receive all my liberty, my memory, my understanding, and my entire will... Give me only your love and your grace, that is enough for me.', 'St. Ignatius of Loyola'),
    (5, 2, 'By God''s grace, I am a man who is temperate, avoiding both gluttony and deficiency.', 'Restrain all thy senses under discipline, and give not thyself up to foolish mirth.', 'Thomas à Kempis', 'The temptation to overwork, overcontrol, or push beyond balance; I will live with restraint instead.', 'The temptation to overconsume, overrest, or seek constant comfort; I will make sure my morning and evening commitments are complete.', 'Where did I notice excess or temperance at work in me today?', 'Take, Lord, and receive all my liberty, my memory, my understanding, and my entire will... Give me only your love and your grace, that is enough for me.', 'St. Ignatius of Loyola'),
    (5, 3, 'By God''s grace, I am a man who is temperate, avoiding both gluttony and deficiency.', 'Love is sober, chaste, stable, quiet, and keeps a guard over all the senses.', 'Thomas à Kempis', 'The desire to do too much, carry too much, or demand too much; I will accept my proper limits instead.', 'The desire to drift toward distraction, or laziness; I will find a way to fast from one thing today.', 'Where did I notice excess or temperance at work in me today?', 'Take, Lord, and receive all my liberty, my memory, my understanding, and my entire will... Give me only your love and your grace, that is enough for me.', 'St. Ignatius of Loyola'),
    (5, 4, 'By God''s grace, I am a man who is temperate, avoiding both gluttony and deficiency.', 'But let us lay the axe to the root, that, being purged from passions, we may possess a quiet mind.', 'Thomas à Kempis', 'The urge to intensify, analyze endlessly, or dominate situations; I will act with simplicity and balance instead.', 'The urge to indulge appetites or avoid sacrifice; I will train my desires instead.', 'Where did I notice excess or temperance at work in me today?', 'Take, Lord, and receive all my liberty, my memory, my understanding, and my entire will... Give me only your love and your grace, that is enough for me.', 'St. Ignatius of Loyola'),
    (5, 5, 'By God''s grace, I am a man who is temperate, avoiding both gluttony and deficiency.', 'Be never altogether idle, but either reading or writing, or praying or meditating, or laboring in something that may be for the common good.', 'Thomas à Kempis', 'The pull toward perfectionism, pressure, or relentless striving; I will receive today peacefully instead.', 'The pull toward comfort, entertainment, or lack of restraint; I will govern myself wisely instead.', 'Where did I notice excess or temperance at work in me today?', 'Take, Lord, and receive all my liberty, my memory, my understanding, and my entire will... Give me only your love and your grace, that is enough for me.', 'St. Ignatius of Loyola'),
    (5, 6, 'By God''s grace, I am a man who is temperate, avoiding both gluttony and deficiency.', 'The man who is not yet perfectly dead to himself is soon tempted and overcome with small and trifling things.', 'Thomas à Kempis', 'The temptation to exceed healthy limits in work, speech, or effort; I will ask a loved one how I can help their efforts.', 'The temptation to seek immediate satisfaction or constant ease; I will choose what strengthens me instead.', 'Where did I notice excess or temperance at work in me today?', 'Take, Lord, and receive all my liberty, my memory, my understanding, and my entire will... Give me only your love and your grace, that is enough for me.', 'St. Ignatius of Loyola'),
    (5, 7, 'By God''s grace, I am a man who is temperate, avoiding both gluttony and deficiency.', 'A true lover of Christ, and a diligent pursuer of virtue, does not hunt after comforts, nor seek such sensible sweetnesses.', 'Thomas à Kempis', 'The battle against excess and disordered intensity; I will live with balance and clarity instead.', 'The battle against indulgence and comfort-seeking; I will embrace discipline with freedom instead.', 'Where did I notice excess or temperance at work in me today?', 'Take, Lord, and receive all my liberty, my memory, my understanding, and my entire will... Give me only your love and your grace, that is enough for me.', 'St. Ignatius of Loyola'),
    (6, 1, 'By God''s grace, I am a man who is kind, avoiding both envy and timidity.', 'A peaceable man does more good than one that is very learned.', 'Thomas à Kempis', 'The pull toward harshness, judgment, or envy; I will be gentle in strength instead.', 'The pull toward attention-seeking, people-pleasing, or avoiding conflict; I will love sincerely instead.', 'Where did I notice envy or kindness at work in me today?', 'Stay with me, [Jesus] and then I shall begin to shine as you shine... O let me praise you, in the way which you love best, by shining on all those around me.', 'St. John Henry Newman'),
    (6, 2, 'By God''s grace, I am a man who is kind, avoiding both envy and timidity.', 'Keep thyself first in peace, and then thou wilt be able to bring others to peace.', 'Thomas à Kempis', 'The temptation to critique, compare, or resent others; I will rejoice in their good instead.', 'The temptation to seek approval or withdraw when unnoticed; I will serve quietly instead.', 'Where did I notice envy or kindness at work in me today?', 'Stay with me, [Jesus] and then I shall begin to shine as you shine... O let me praise you, in the way which you love best, by shining on all those around me.', 'St. John Henry Newman'),
    (6, 3, 'By God''s grace, I am a man who is kind, avoiding both envy and timidity.', 'Nothing is sweeter than love, nothing stronger, nothing higher, nothing more generous, nothing more pleasant, nothing fuller or better in Heaven or on earth.', 'Thomas à Kempis', 'The desire to compete, correct harshly, or diminish others; I will speak words of gratitude and kindness instead.', 'The desire to be admired, included, or left undisturbed by others; I will seek to encourage others instead.', 'Where did I notice envy or kindness at work in me today?', 'Stay with me, [Jesus] and then I shall begin to shine as you shine... O let me praise you, in the way which you love best, by shining on all those around me.', 'St. John Henry Newman'),
    (6, 4, 'By God''s grace, I am a man who is kind, avoiding both envy and timidity.', 'Love is swift, sincere, pious, pleasant, and delightful; strong, patient, faithful, prudent, long suffering, courageous, and never seeking itself.', 'Thomas à Kempis', 'The urge to judge motives, hold grudges, or magnify faults; I will practice mercy instead.', 'The urge to seek attention, avoid discomfort, or neglect real needs; I will be attentive to the needs of others.', 'Where did I notice envy or kindness at work in me today?', 'Stay with me, [Jesus] and then I shall begin to shine as you shine... O let me praise you, in the way which you love best, by shining on all those around me.', 'St. John Henry Newman'),
    (6, 5, 'By God''s grace, I am a man who is kind, avoiding both envy and timidity.', 'Love is swift, sincere, kind, pleasant, and delightful.', 'Thomas à Kempis', 'The pull toward resentment, irritation, or superiority; I will honor others gladly instead.', 'The pull toward vanity, shallow affection, or fear of rejection; I will bless others with my words without desiring attention.', 'Where did I notice envy or kindness at work in me today?', 'Stay with me, [Jesus] and then I shall begin to shine as you shine... O let me praise you, in the way which you love best, by shining on all those around me.', 'St. John Henry Newman'),
    (6, 6, 'By God''s grace, I am a man who is kind, avoiding both envy and timidity.', 'Nature is covetous, and receives more willingly than it gives. It loves to have its own private possessions. Grace, however, is kind and openhearted.', 'Thomas à Kempis', 'The temptation to compare myself or withhold kindness; I will encourage others freely instead.', 'The temptation to seek affirmation or remain emotionally self-centered; I will give myself generously instead.', 'Where did I notice envy or kindness at work in me today?', 'Stay with me, [Jesus] and then I shall begin to shine as you shine... O let me praise you, in the way which you love best, by shining on all those around me.', 'St. John Henry Newman'),
    (6, 7, 'By God''s grace, I am a man who is kind, avoiding both envy and timidity.', 'O how kind is Your spirit, Lord, Who in order to show Your sweetness toward Your children, deign to feed them with the sweetest of bread, bread come down from heaven!', 'Thomas à Kempis', 'The battle against envy, harshness, and resentment; I will choose charity and goodwill instead.', 'The battle against vanity, approval-seeking, and neglect of others; I will love with sincerity instead.', 'Where did I notice envy or kindness at work in me today?', 'Stay with me, [Jesus] and then I shall begin to shine as you shine... O let me praise you, in the way which you love best, by shining on all those around me.', 'St. John Henry Newman'),
    (7, 1, 'By God''s grace, I am a man who is diligent, avoiding both sloth and workaholism.', 'Labor a little now, and soon you shall find great rest, in truth, eternal joy; for if you continue faithful and diligent in doing, God will undoubtedly be faithful and generous in rewarding.', 'Thomas à Kempis', 'The pull toward obsession, paralysis, or pride in busyness; I will find time of rest and enjoy leisure with my family.', 'The pull toward procrastination, laziness, or bare minimum; I will finish faithfully instead.', 'Where did I notice sloth or diligence at work in me today?', 'Illuminate my darkness, O Lord, and give me true understanding, that I may know what is of You and what is not. Amen.', 'St. Bonaventure'),
    (7, 2, 'By God''s grace, I am a man who is diligent, avoiding both sloth and workaholism.', 'A man makes the most progress and merits the most grace precisely in those matters wherein he gains the greatest victories over self and conquer, but a diligent will. True, each one has his own difficulties to meet and conquer, but a diligent and sincere man will make greater progress even though he has more passions than one who is more even-tempered but less concerned about virtue.', 'Thomas à Kempis', 'The temptation to overwork, overplan, or carry unnecessary burdens; I will labor with peace instead.', 'The temptation to delay, avoid effort, or waste time; I will acknowledge moments of procrastination and get to it.', 'Where did I notice sloth or diligence at work in me today?', 'Illuminate my darkness, O Lord, and give me true understanding, that I may know what is of You and what is not. Amen.', 'St. Bonaventure'),
    (7, 3, 'By God''s grace, I am a man who is diligent, avoiding both sloth and workaholism.', 'Be watchful and diligent in God''s service and often think of why you left the world and came here. Was it not that you might live for God and become a spiritual man?', 'Thomas à Kempis', 'The desire to control every detail or prove my worth through work; I will work as a servant of God instead.', 'The desire to coast, distract myself, or abandon difficult tasks; I will persevere steadily instead.', 'Where did I notice sloth or diligence at work in me today?', 'Illuminate my darkness, O Lord, and give me true understanding, that I may know what is of You and what is not. Amen.', 'St. Bonaventure'),
    (7, 4, 'By God''s grace, I am a man who is diligent, avoiding both sloth and workaholism.', 'The better you dispose yourself to suffer, the greater is the reward promised you. Thus, you will suffer more easily if your mind and habits are diligently trained to it.', 'Thomas à Kempis', 'The urge to overanalyze or hesitate because of perfectionism; I will work with simple desires for completion.', 'The urge to take shortcuts, drift, or neglect responsibilities; I will do things the right way first.', 'Where did I notice sloth or diligence at work in me today?', 'Illuminate my darkness, O Lord, and give me true understanding, that I may know what is of You and what is not. Amen.', 'St. Bonaventure'),
    (7, 5, 'By God''s grace, I am a man who is diligent, avoiding both sloth and workaholism.', 'My child, you must strive diligently to be inwardly free, to have mastery over yourself everywhere, in every external act and occupation, that all things be subject to you and not you to them, that you be the master and director of your actions, not a slave or a mere hired servant.', 'Thomas à Kempis', 'The pull toward anxious striving, frustration, or unhealthy pressure; I will work with trust and balance instead.', 'The pull toward comfort, excuses, or lack of discipline; I will embrace responsibility instead.', 'Where did I notice sloth or diligence at work in me today?', 'Illuminate my darkness, O Lord, and give me true understanding, that I may know what is of You and what is not. Amen.', 'St. Bonaventure'),
    (7, 6, 'By God''s grace, I am a man who is diligent, avoiding both sloth and workaholism.', 'As our intention is, so will be our progress; and he who desires perfection must be very diligent. If the strong-willed man fails frequently, what of the man who makes up his mind seldom or half-heartedly?', 'Thomas à Kempis', 'The temptation to make work an idol or lose sight of what matters most; I will labor faithfully and humbly instead.', 'The temptation to quit early, avoid sacrifice, or settle for mediocrity; I will remain steadfast instead.', 'Where did I notice sloth or diligence at work in me today?', 'Illuminate my darkness, O Lord, and give me true understanding, that I may know what is of You and what is not. Amen.', 'St. Bonaventure'),
    (7, 7, 'By God''s grace, I am a man who is diligent, avoiding both sloth and workaholism.', 'How conducive it is for the keeping of heavenly grace, to fly the gaze of men, not to seek abroad things which seem to cause admiration, but to follow with the utmost diligence those which give fervor and amendment of life! How many have been harmed by having their virtue known and praised too hastily! And how truly profitable it has been when grace remained hidden during this frail life, which is all temptation and warfare!', 'Thomas à Kempis', 'The battle against thinking only of my own goals; I will work for the good of someone else''s goals.', 'The battle against working hard to be liked or left undisturbed; I will work in hidden ways that are hard for me.', 'Where did I notice sloth or diligence at work in me today?', 'Illuminate my darkness, O Lord, and give me true understanding, that I may know what is of You and what is not. Amen.', 'St. Bonaventure')
) as d(week_number, day_number, identity_reading, wisdom_quote, wisdom_author, sword_option_1, sword_option_2, spade_prompt, closing_prayer, closing_prayer_author)
on d.week_number = w.week_number;
